# Generated by Django 4.0.4 on 2022-04-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('dead_line', models.DateTimeField()),
                ('task_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
