# Generated by Django 4.0.4 on 2022-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todoapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='image',
            field=models.ImageField(default='download.png', upload_to='images/'),
        ),
    ]
