# Generated by Django 4.0.4 on 2022-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todoapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='dead_line',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
